version: '3'
services:
  tomcat-server:
    container_name: tomcat-server
    build: ./server
    ports:
      - "8080:8080"
      - "8000:8000"
    links:
      - db

  db:
    container_name: db
    build: ./DockerDb
    expose:
      - "5432"

  adminer:
      container_name: dbAdmin
      image: adminer
      restart: always
      ports:
        - 8082:8080
      links:
        - db