version: '3'
services:
  tomcat-server:
    container_name: tomcat-server
    build: ./server
    ports:
      - "8080:8080"
    links:
      - db
  db:
    container_name: db
    build: ./DockerDb
    expose:
      - "5432"
  adminer:
      image: adminer
      restart: always
      ports:
        - 8082:8080