version: '3'
services:
  tomcat-server:
    container_name: tomcat-server
    build: ./server
    ports:
      - "8080:8080"
      - "8000:8000"
    links:
      - db

  db:
    container_name: db
    build: ./DockerDb
    expose:
      - "5432"
    ports:
      - "5434:5432"